//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projCarWashV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer_Data()
        {
            this.Transaction_Data = new HashSet<Transaction_Data>();
        }
    
        public int ID_Customer { get; set; }
        public string Customer_Name { get; set; }
        public string Phone_Customer { get; set; }
        public string Address_Customer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_Data> Transaction_Data { get; set; }
    }
}
