//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projCarWashV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail_Washing_Data
    {
        public int ID_Detail { get; set; }
        public Nullable<int> ID_Transaction { get; set; }
        public Nullable<int> ID_Type { get; set; }
    
        public virtual Transaction_Data Transaction_Data { get; set; }
        public virtual Price Price { get; set; }
    }
}
