//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projCarWashV2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjCarWashEntities : DbContext
    {
        public ProjCarWashEntities()
            : base("name=ProjCarWashEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer_Data> Customer_Data { get; set; }
        public virtual DbSet<Detail_Washing_Data> Detail_Washing_Data { get; set; }
        public virtual DbSet<Price> Price { get; set; }
        public virtual DbSet<Transaction_Data> Transaction_Data { get; set; }
    }
}
